// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class Appointment
{
    [Key]
    public int AppointmentId { get; set; }

    public int ClientId { get; set; }

    public int StuffId { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [StringLength(50)]
    public string AppointmentType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AppointmentDate { get; set; }

    [Required]
    [StringLength(200)]
    public string Location { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Required]
    [StringLength(500)]
    public string Summary { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Appointments")]
    public virtual Client Client { get; set; }
}