// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class City
{
    [Key]
    public int CityId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();
}