// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class Client
{
    [Key]
    public int ClientId { get; set; }

    [Required]
    [StringLength(100)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(100)]
    public string LastName { get; set; }

    [Required]
    [StringLength(14)]
    [Unicode(false)]
    public string NationalId { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(500)]
    public string Address { get; set; }

    [StringLength(50)]
    public string ClientType { get; set; }

    [StringLength(250)]
    public string IDImageFrontPath { get; set; }

    [StringLength(250)]
    public string IDImageBackPath { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [InverseProperty("Client")]
    public virtual ICollection<ClientDocument> ClientDocuments { get; set; } = new List<ClientDocument>();

    [InverseProperty("Client")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}