// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class ClientDocument
{
    [Key]
    public int ClientDocumentId { get; set; }

    public int ClientId { get; set; }

    [Required]
    [StringLength(500)]
    public string DocumentName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RenewalDate { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("ClientDocuments")]
    public virtual Client Client { get; set; }
}