// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class OfficeStuff
{
    [Key]
    public int StuffId { get; set; }

    public int OfficeId { get; set; }

    [Required]
    [StringLength(150)]
    public string Name { get; set; }

    [Required]
    [StringLength(150)]
    public string JobTitle { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("OfficeId")]
    [InverseProperty("OfficeStuffs")]
    public virtual OfficeProfile Office { get; set; }

    [InverseProperty("Stuff")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}