// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class OfficeProfile
{
    [Key]
    public int OfficeId { get; set; }

    [Required]
    [StringLength(500)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string ResponsabltyPerson { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Moblie { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(150)]
    public string Website { get; set; }

    [StringLength(250)]
    public string LogoPath { get; set; }

    public int? WorkStart { get; set; }

    public int? WorkEnd { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Office")]
    public virtual ICollection<OfficeStuff> OfficeStuffs { get; set; } = new List<OfficeStuff>();
}