// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

[Index("TransactionId", Name = "IX_Payments", IsUnique = true)]
public partial class Payment
{
    [Key]
    public int PaymentId { get; set; }

    public int TransactionId { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentType { get; set; }

    [Column(TypeName = "decimal(7, 2)")]
    public decimal AmountService { get; set; }

    [Column(TypeName = "decimal(7, 2)")]
    public decimal? TaxValue { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PaymentDate { get; set; }

    [Required]
    [StringLength(50)]
    public string ReceiptNumber { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("Payment")]
    public virtual Transaction Transaction { get; set; }
}