// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class PropertyType
{
    [Key]
    public int PropertyTypeId { get; set; }

    public int PropertyCategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("PropertyType")]
    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    [ForeignKey("PropertyCategoryId")]
    [InverseProperty("PropertyTypes")]
    public virtual ProppertyCategory PropertyCategory { get; set; }
}