// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class PropertyImage
{
    [Key]
    public int PropertyImageId { get; set; }

    public int PropertyId { get; set; }

    [Required]
    [StringLength(255)]
    public string ImagePath { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("PropertyId")]
    [InverseProperty("PropertyImages")]
    public virtual Property Property { get; set; }
}