// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class ProppertyCategory
{
    [Key]
    public int PropertyCategoryId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("PropertyCategory")]
    public virtual ICollection<PropertyType> PropertyTypes { get; set; } = new List<PropertyType>();
}