// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class Template
{
    [Key]
    public int TemplateId { get; set; }

    [Required]
    [StringLength(200)]
    public string TemplateName { get; set; }

    [Required]
    [StringLength(250)]
    public string TemplateContentPath { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Template")]
    public virtual ICollection<TransactionDocument> TransactionDocuments { get; set; } = new List<TransactionDocument>();
}