// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class TransactionsStage
{
    [Key]
    public int TransactionsStageId { get; set; }

    public int TransactionId { get; set; }

    [Required]
    [StringLength(50)]
    public string StageName { get; set; }

    public bool? StageStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpectedEndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CompletedDate { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("TransactionsStages")]
    public virtual Transaction Transaction { get; set; }
}