// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

[Table("TransactionStatus")]
public partial class TransactionStatus
{
    [Key]
    public int TransactionStatusId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("TransactionStatus")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}