// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class Transaction
{
    [Key]
    public int TransactionId { get; set; }

    public int ClientId { get; set; }

    public int PropertyId { get; set; }

    public int ServiceTypeId { get; set; }

    public int StuffId { get; set; }

    public int TransactionStatusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StarDate { get; set; }

    [Column(TypeName = "decimal(20, 2)")]
    public decimal? TotalFees { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("Transactions")]
    public virtual Client Client { get; set; }

    [InverseProperty("Transaction")]
    public virtual Payment Payment { get; set; }

    [ForeignKey("PropertyId")]
    [InverseProperty("Transactions")]
    public virtual Property Property { get; set; }

    [ForeignKey("ServiceTypeId")]
    [InverseProperty("Transactions")]
    public virtual ServerType ServiceType { get; set; }

    [ForeignKey("StuffId")]
    [InverseProperty("Transactions")]
    public virtual OfficeStuff Stuff { get; set; }

    [InverseProperty("Transaction")]
    public virtual ICollection<TransactionDocument> TransactionDocuments { get; set; } = new List<TransactionDocument>();

    [InverseProperty("Transaction")]
    public virtual ICollection<TransactionFee> TransactionFees { get; set; } = new List<TransactionFee>();

    [ForeignKey("TransactionStatusId")]
    [InverseProperty("Transactions")]
    public virtual TransactionStatus TransactionStatus { get; set; }

    [InverseProperty("Transaction")]
    public virtual ICollection<TransactionsStage> TransactionsStages { get; set; } = new List<TransactionsStage>();
}