// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class TransactionDocument
{
    [Key]
    public int TransactionDocument_Id { get; set; }

    public int TransactionId { get; set; }

    [Required]
    [StringLength(150)]
    public string DocumentType { get; set; }

    public int TemplateId { get; set; }

    [Required]
    [StringLength(150)]
    public string DocumentName { get; set; }

    [Required]
    [StringLength(250)]
    public string FilePath { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("TemplateId")]
    [InverseProperty("TransactionDocuments")]
    public virtual Template Template { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("TransactionDocuments")]
    public virtual Transaction Transaction { get; set; }
}