// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBGetCodeFirst.Models;

public partial class TransactionFee
{
    [Key]
    public int TransactionFeeId { get; set; }

    public int TransactionId { get; set; }

    [Required]
    [StringLength(150)]
    public string ItemName { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal Fees { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("TransactionFees")]
    public virtual Transaction Transaction { get; set; }
}